builders:
  flutter_mybatis:
    import: "package:flutter_mybatis_generator/flutter_mybatis_generator.dart"
    builder_factories: ["mapperBuilder"]
    build_extensions: {".dart": [".flutter_mybatis.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
