// source_gen 2.0.0의 Generator API는 아직 구 element 모델(Element/ClassElement)을
// 넘겨줍니다. analyzer 8.x가 이를 deprecated 처리했지만 source_gen이 새 모델
// (Element2)로 올라가기 전까지는 이쪽을 써야 합니다.
// ignore_for_file: deprecated_member_use

import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/nullability_suffix.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'xml_statements.dart';

const _annotations = 'package:flutter_mybatis/src/annotations.dart';

/// Generates the implementation of an abstract class annotated with
/// `@MybatisMapper`.
class MapperGenerator extends Generator {
  static const _mapperChecker = TypeChecker.fromUrl('$_annotations#MybatisMapper');
  static const _paramChecker = TypeChecker.fromUrl('$_annotations#Param');

  /// Annotation name to statement kind.
  static const _methodAnnotations = <String, _Kind>{
    'Select': _Kind.selectList,
    'SelectOne': _Kind.selectOne,
    'SelectCount': _Kind.selectCount,
    'Insert': _Kind.insert,
    'Update': _Kind.update,
    'Delete': _Kind.delete,
  };

  @override
  Future<String?> generate(LibraryReader library, BuildStep buildStep) async {
    final buffer = StringBuffer();

    for (final element in library.allElements) {
      if (element is! ClassElement) continue;

      final annotation = _mapperChecker.firstAnnotationOf(element);
      if (annotation == null) continue;

      if (!element.isAbstract) {
        throw InvalidGenerationSourceError(
          '@MybatisMapper can only be applied to an abstract class.',
          element: element,
        );
      }

      final reader = ConstantReader(annotation);
      final namespace = reader.read('namespace').stringValue;
      final xmlPath = reader.read('xml').isNull ? null : reader.read('xml').stringValue;

      final statements = xmlPath == null
          ? null
          : await loadStatements(buildStep, xmlPath, namespace, element);

      buffer.writeln(_generateClass(element, namespace, statements));
    }

    return buffer.isEmpty ? null : buffer.toString();
  }

  String _generateClass(
    ClassElement element,
    String namespace,
    Map<String, String>? statements,
  ) {
    final name = element.name;
    final buffer = StringBuffer()
      ..writeln('/// Implementation of [$name], generated by flutter_mybatis_generator.')
      ..writeln('class _\$$name extends Mapper implements $name {')
      ..writeln('  _\$$name(super.session);')
      ..writeln()
      ..writeln('  @override')
      ..writeln("  String get namespace => '$namespace';");

    for (final method in element.methods) {
      if (!method.isAbstract) continue;
      buffer
        ..writeln()
        ..writeln(_generateMethod(method, namespace, statements));
    }

    buffer.writeln('}');
    return buffer.toString();
  }

  String _generateMethod(
    MethodElement method,
    String namespace,
    Map<String, String>? statements,
  ) {
    final found = _resolveKind(method);
    final kind = found.kind;
    final statementId = found.id ?? method.name;
    final fullId = '$namespace.$statementId';

    // XML 검증: statement가 실제로 있는지, 종류가 맞는지
    if (statements != null) {
      final actualType = statements[statementId];
      if (actualType == null) {
        final available = statements.keys.toList()..sort();
        throw InvalidGenerationSourceError(
          'Statement not found in XML: "$fullId"\n'
          'available ids: ${available.join(', ')}',
          element: method,
        );
      }
      final expected = kind.xmlTag;
      if (actualType != expected) {
        throw InvalidGenerationSourceError(
          'Statement kind mismatch: "$fullId" is <$actualType> '
          'but was declared as <$expected>.',
          element: method,
        );
      }
    }

    final signature = _signature(method);
    final paramsExpression = _paramsExpression(method, kind);
    final call = kind.call(fullId, paramsExpression, found.column, method);

    return '  @override\n  $signature => $call;';
  }

  _Found _resolveKind(MethodElement method) {
    for (final entry in _methodAnnotations.entries) {
      final checker = TypeChecker.fromUrl('$_annotations#${entry.key}');
      final annotation = checker.firstAnnotationOf(method);
      if (annotation == null) continue;

      final reader = ConstantReader(annotation);
      final idField = reader.read('id');
      final column = entry.value == _Kind.selectCount
          ? reader.read('column').stringValue
          : 'CNT';

      return _Found(
        entry.value,
        idField.isNull ? null : idField.stringValue,
        column,
      );
    }

    throw InvalidGenerationSourceError(
      'One of @Select / @SelectOne / @SelectCount / @Insert / @Update / '
      '@Delete is required.',
      element: method,
    );
  }

  /// Reproduces the declared method signature verbatim.
  String _signature(MethodElement method) {
    final positional = <String>[];
    final optional = <String>[];
    final named = <String>[];

    for (final p in method.parameters) {
      final type = p.type.getDisplayString();
      final defaultValue =
          p.defaultValueCode == null ? '' : ' = ${p.defaultValueCode}';

      if (p.isRequiredPositional) {
        positional.add('$type ${p.name}');
      } else if (p.isOptionalPositional) {
        optional.add('$type ${p.name}$defaultValue');
      } else {
        final required = p.isRequiredNamed ? 'required ' : '';
        named.add('$required$type ${p.name}$defaultValue');
      }
    }

    final parts = <String>[...positional];
    if (optional.isNotEmpty) parts.add('[${optional.join(', ')}]');
    if (named.isNotEmpty) parts.add('{${named.join(', ')}}');

    final returnType = method.returnType.getDisplayString();
    return '$returnType ${method.name}(${parts.join(', ')})';
  }

  /// Builds the parameter map expression passed to the statement.
  ///
  /// A single `Map<String, dynamic>` parameter is forwarded as-is; otherwise
  /// a map is assembled from `@Param` names, falling back to parameter names.
  String _paramsExpression(MethodElement method, _Kind kind) {
    // Paging arguments only exist on selectList. Everywhere else a parameter
    // named `limit` is just a parameter, and swallowing it would silently
    // break the statement.
    final paging = kind == _Kind.selectList;
    final dataParams = method.parameters
        .where((p) => !(paging && (p.name == 'limit' || p.name == 'offset')))
        .toList();

    if (dataParams.isEmpty) return 'const <String, dynamic>{}';

    if (dataParams.length == 1 && _isParamMap(dataParams.first.type)) {
      return dataParams.first.name;
    }

    final entries = dataParams.map((p) {
      final annotation = _paramChecker.firstAnnotationOf(p);
      final key = annotation == null
          ? p.name
          : ConstantReader(annotation).read('name').stringValue;
      return "'$key': ${p.name}";
    });

    return '<String, dynamic>{${entries.join(', ')}}';
  }

  static bool _isParamMap(DartType type) {
    if (type is! InterfaceType) return false;
    if (type.element.name != 'Map') return false;
    if (type.typeArguments.length != 2) return false;
    return type.typeArguments.first.isDartCoreString;
  }
}

enum _Kind {
  selectList,
  selectOne,
  selectCount,
  insert,
  update,
  delete;

  /// The XML tag this kind corresponds to.
  String get xmlTag {
    switch (this) {
      case _Kind.selectList:
      case _Kind.selectOne:
      case _Kind.selectCount:
        return 'select';
      case _Kind.insert:
        return 'insert';
      case _Kind.update:
        return 'update';
      case _Kind.delete:
        return 'delete';
    }
  }

  /// The session call to generate.
  String call(
    String fullId,
    String params,
    String countColumn,
    MethodElement method,
  ) {
    switch (this) {
      case _Kind.selectList:
        final paging = _pagingArgs(method);
        return "session.selectList('$fullId', $params$paging)";
      case _Kind.selectOne:
        return "session.selectOne('$fullId', $params)";
      case _Kind.selectCount:
        return "session.selectCount('$fullId', $params, "
            "countColumn: '$countColumn')";
      case _Kind.insert:
        return "session.insert('$fullId', $params)";
      case _Kind.update:
        return "session.update('$fullId', $params)";
      case _Kind.delete:
        return "session.delete('$fullId', $params)";
    }
  }

  /// Forwards `limit` / `offset` parameters when present.
  static String _pagingArgs(MethodElement method) {
    final buffer = StringBuffer();
    for (final p in method.parameters) {
      if (p.name == 'limit' || p.name == 'offset') {
        buffer.write(', ${p.name}: ${p.name}');
      }
    }
    return buffer.toString();
  }
}

class _Found {
  final _Kind kind;
  final String? id;
  final String column;

  _Found(this.kind, this.id, this.column);
}

/// Nullability helper.
extension on DartType {
  // ignore: unused_element
  bool get isNullable => nullabilitySuffix == NullabilitySuffix.question;
}
