// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'person_mapper.dart';

// **************************************************************************
// MapperGenerator
// **************************************************************************

/// Implementation of [PersonMapper], generated by flutter_mybatis_generator.
class _$PersonMapper extends Mapper implements PersonMapper {
  _$PersonMapper(super.session);

  @override
  String get namespace => 'PersonMapper';

  @override
  Future<List<Map<String, dynamic>>> search(Map<String, dynamic> params) =>
      session.selectList('PersonMapper.selectList', params);

  @override
  Future<List<Map<String, dynamic>>> searchPaged(Map<String, dynamic> params,
          {int? limit, int? offset}) =>
      session.selectList('PersonMapper.selectList', params,
          limit: limit, offset: offset);

  @override
  Future<Map<String, dynamic>?> findById(int id) =>
      session.selectOne('PersonMapper.selectById', <String, dynamic>{'ID': id});

  @override
  Future<int> countAll(bool activeOnly) => session.selectCount(
      'PersonMapper.selectCount', <String, dynamic>{'activeOnly': activeOnly},
      countColumn: 'CNT');

  @override
  Future<List<Map<String, dynamic>>> sorted(String sortBy, String sortDir) =>
      session.selectList('PersonMapper.selectSorted',
          <String, dynamic>{'sortBy': sortBy, 'sortDir': sortDir});

  @override
  Future<int> add(Map<String, dynamic> person) =>
      session.insert('PersonMapper.insert', person);

  @override
  Future<int> addWithSelectKey(Map<String, dynamic> person) =>
      session.insert('PersonMapper.insertWithSelectKey', person);

  @override
  Future<int> modify(Map<String, dynamic> person) =>
      session.update('PersonMapper.update', person);

  @override
  Future<int> remove(int id) =>
      session.delete('PersonMapper.delete', <String, dynamic>{'ID': id});

  @override
  Future<int> removeAll(List<int> ids) =>
      session.delete('PersonMapper.deleteByIds', <String, dynamic>{'ids': ids});
}
