// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'petstore_mapper.dart';

// **************************************************************************
// MapperGenerator
// **************************************************************************

/// Implementation of [PetStoreMapper], generated by flutter_mybatis_generator.
class _$PetStoreMapper extends Mapper implements PetStoreMapper {
  _$PetStoreMapper(super.session);

  @override
  String get namespace => 'PetStoreMapper';

  @override
  Future<List<Map<String, dynamic>>> categories() => session.selectList(
      'PetStoreMapper.selectCategoryList', const <String, dynamic>{});

  @override
  Future<Map<String, dynamic>?> category(String catId) => session.selectOne(
      'PetStoreMapper.selectCategory', <String, dynamic>{'CATID': catId});

  @override
  Future<List<Map<String, dynamic>>> products(Map<String, dynamic> params,
          {int? limit, int? offset}) =>
      session.selectList('PetStoreMapper.selectProductList', params,
          limit: limit, offset: offset);

  @override
  Future<Map<String, dynamic>?> product(String productId) => session.selectOne(
      'PetStoreMapper.selectProduct',
      <String, dynamic>{'PRODUCTID': productId});

  @override
  Future<int> productCount(String? catId) => session.selectCount(
      'PetStoreMapper.selectProductCount', <String, dynamic>{'CATID': catId},
      countColumn: 'CNT');

  @override
  Future<List<Map<String, dynamic>>> itemsOf(
          String productId, bool inStockOnly) =>
      session.selectList(
          'PetStoreMapper.selectItemListByProduct', <String, dynamic>{
        'PRODUCTID': productId,
        'inStockOnly': inStockOnly
      });

  @override
  Future<Map<String, dynamic>?> item(String itemId) => session.selectOne(
      'PetStoreMapper.selectItem', <String, dynamic>{'ITEMID': itemId});

  @override
  Future<int> decreaseInventory(String itemId, int qty) => session.update(
      'PetStoreMapper.decreaseInventory',
      <String, dynamic>{'ITEMID': itemId, 'QTY': qty});

  @override
  Future<int> createAccount(Map<String, dynamic> account) =>
      session.insert('PetStoreMapper.insertAccount', account);

  @override
  Future<Map<String, dynamic>?> account(String userId) => session.selectOne(
      'PetStoreMapper.selectAccount', <String, dynamic>{'USERID': userId});

  @override
  Future<int> updateAccount(Map<String, dynamic> account) =>
      session.update('PetStoreMapper.updateAccount', account);

  @override
  Future<int> createOrder(Map<String, dynamic> order) =>
      session.insert('PetStoreMapper.insertOrder', order);

  @override
  Future<int> createOrderLine(Map<String, dynamic> line) =>
      session.insert('PetStoreMapper.insertOrderLine', line);

  @override
  Future<List<Map<String, dynamic>>> orders(Map<String, dynamic> params) =>
      session.selectList('PetStoreMapper.selectOrderList', params);

  @override
  Future<Map<String, dynamic>?> order(int orderId) => session.selectOne(
      'PetStoreMapper.selectOrder', <String, dynamic>{'ORDERID': orderId});

  @override
  Future<List<Map<String, dynamic>>> orderLines(int orderId) =>
      session.selectList('PetStoreMapper.selectOrderLineList',
          <String, dynamic>{'ORDERID': orderId});

  @override
  Future<int> updateOrderStatus(int orderId, String status) => session.update(
      'PetStoreMapper.updateOrderStatus',
      <String, dynamic>{'ORDERID': orderId, 'STATUS': status});

  @override
  Future<int> deleteOrder(int orderId) => session.delete(
      'PetStoreMapper.deleteOrder', <String, dynamic>{'ORDERID': orderId});

  @override
  Future<int> deleteOrderLines(int orderId) => session.delete(
      'PetStoreMapper.deleteOrderLines', <String, dynamic>{'ORDERID': orderId});
}
